import type { NextPage } from "next";
import Head from "next/head";
import Header from "~/components/ui/Header";
import Footer from "~/components/ui/Footer";
import { Button } from "~/components/ui/Button";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="min-h-screen">
        <section className="flex items-center h-screen">
          <div className=" flex flex-col items-center justify-center flex-1">
            <h1 className="text-7xl font-bold">RevisionStudy</h1>
            <p className="text-xl">
              A simple app to help you revise your vocabulary.
            </p>
            <div className="my-6 flex flex-col w-3/4  gap-4">
              <Button variant="primary" className="w-full">
                Get Started!
              </Button>
              <Button variant="primary" outline className="w-full">
                Explore tests
              </Button>
            </div>
          </div>
          <div className="hero_img flex-1">djsosdfo</div>
        </section>
        <section className="flex gap-4 w-full p-4">
          {[1, 2, 3, 4, 5].map((i) => (
            <div
              key={i}
              className="p-12 relative overflow-hidden flex-1 text-center group bg-gray-100 cursor-pointer hover:bg-gray-300 rounded"
            >
              Features
              <div className="absolute top-0 left-0 w-full group-hover:opacity-100 group-hover:translate-y-0 h-full transition-all translate-y-8 opacity-0 bg-red-100">
                kkk
              </div>
            </div>
          ))}
        </section>
        <div className="flex p-8 items-center text-5xl justify-center">
          We are 1% for something
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
